import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import Hero from "../components/Hero";
import Popular from "../components/Popular";

export default function Home() {
  const [movies, setMovies] = useState([]);
  const API_URL =
    "https://api.themoviedb.org/3/movie/popular?api_key=c078b2b51eb7108473306fd02e3c25d5";

  useEffect(() => {
    fetch(API_URL)
      .then((res) => res.json())
      .then((data) => {
        setMovies(data.results);
      });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-black overflow-hidden">
        {/* Hero */}
        <Hero />
        {/* Popular on Netflix */}
        <Popular movies={movies} />
        {/* Recently Watched */}
        <Popular movies={movies} />
      </div>
    </div>
  );
}
